if &compatible
  set nocompatible
endif

" Make vim respect XDG directories
:source ~/.config/vim/xdg.vim
" Shortcut to remap colemak to qwerty based keybindings
nnoremap <silent> gm :runtime colemak-remap.vim<CR>

filetype off
filetype plugin indent on

if has('gui_running')
  " started as gvim which has a light background
  set background=light
  " Make shift-insert work like in Xterm
  map <S-Insert> <MiddleMouse>
  map! <S-Insert> <MiddleMouse>
else
  " started from console, so we'll most likely have a dark background
  set background=dark
endif
set autoindent                  " always set autoindenting on
set backspace=indent,eol,start  " allow backspacing over everything in insert mode
set colorcolumn=81              " indicate when going over 80 columns
set encoding=utf-8              " always use utf-8 encoding
set expandtab                   " expand tabs to spaces
set fileformat=unix             " use unix file format
set history=50                  " keep 50 lines of command line history
set incsearch                   " do incremental searching
set list                        " enable list mode to display differences between tabs and spaces
set listchars=tab:»˙,trail:•    " set the characters used to identify tabs and trailing spaces
set nonumber                    " don't show line numbers
set ruler                       " show the cursor position all the time
set shiftwidth=4                " shift 4 spaces for indentation
set showcmd                     " display incomplete commands
set softtabstop=4               " use 4 spaces for tab
set tabstop=8                   " place tabstop on 8 spaces, makes unexpanded tabs stand out
set wrap                        " wrap text

highlight TrailWhitespace ctermbg=red guibg=darkred
highlight UnwantedTab ctermbg=red guibg=darkred

if has("autocmd")
  " support for autocommands has been enabled
  autocmd BufNewFile,BufRead *.py,*.pyw,*.c,*.h match TrailWhitespace /\s\+$/
  autocmd BufNewFile,BufRead *.py,*.pyw,*.c,*.h match UnwantedTab /\t/

  autocmd BufRead,BufNewFile *.hcl set filetype=terraform

  autocmd FileType bzl          :runtime bzl.vim
  autocmd FileType c            :runtime c.vim
  autocmd FileType cpp          :runtime cpp.vim
  autocmd FileType css          :runtime css.vim
  autocmd FileType go           :runtime go.vim
  autocmd FileType html         :runtime html.vim
  autocmd FileType javascript   :runtime js.vim
  autocmd FileType json         :runtime json.vim
  autocmd FileType markdown     :runtime md.vim
  autocmd FileType php          :runtime php.vim
  autocmd FileType python       :runtime python.vim
  autocmd FileType ruby         :runtime ruby.vim
  autocmd FileType scss         :runtime scss.vim
  autocmd FileType sh           :runtime sh.vim
  autocmd FileType terraform    :runtime tf.vim
  autocmd FileType text         :runtime txt.vim
  autocmd FileType typescript   :runtime ts.vim
  autocmd FileType xml          :runtime xml.vim
  autocmd FileType yaml         :runtime yaml.vim

  nnoremap <buffer> <silent> <LocalLeader>= :ALEFix<CR>
endif

" If the terminal supports colors or vim is started in gui, switch syntax
" highlighting on.
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Enable folding with the spacebar
nnoremap <space> za

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>
