# pattern: Can either be the exact "app_name" (app_id/class) of the window or a regex string in the format of `"/{regex}/"` which will match the window "title".
# icon: Your beautiful icon
fallback = ''

[matching]
'discord' = ''
'/Signal/' = ''
'Slack' = ''
'Steam' = ''
'vlc' = ''
'/Google (Duo|Meet)/' = ''
'noson-gui' = ''
'/Pararius Mail/' = ''
'/Pararius – Calendar/' = ''
'jetbrains-webstorm' = ''
'Spotify' = ''
'Webstorm' = ''
'PHPstorm' = ''
'Alacritty' = ''
'terminator' = ''
'kitty' = ''
'firefox' = ''
'Google-chrome' = ''
'chromium' = ''
'/JustDoIt|Just do it/' = ''
'sublime_text' = ''
