theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "pacman"
interval = 600
format = "Updates: {pacman}/{aur}"
format_singular = "{both} updates available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux |linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "yay -Qua"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
unit = "GiB"
format = "{icon}{used}/{total} {unit} ({available}{unit} free)"

[[block]]
block = "net"
#device = "lo"
#format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"
format = "{ip} {speed_down} {graph_down}"
interval = 5
use_bits = false

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
format = "%F %R"
interval = 1
